version: '3.8'

services:
  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgresql_data:/var/lib/postgresql/data/
    env_file:
      - .env_postgresql

  django:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
    ports:
      - "8000:8000"
    volumes:
      - ./django:/property_rental
    command: >
      sh -c "
        sh /scripts/wait_for_db.sh &&
        sh /scripts/collect_static.sh &&
        sh /scripts/migrate.sh &&
        sh /scripts/run_server.sh
      "
    user: root
    env_file:
      - .env_postgresql
    depends_on:
      - postgresql

#  tests:
#    build:
#      context: .
#      dockerfile: Dockerfile-postgresql
#    command: >
#      sh -c "
#        sh /scripts/run_tests.sh
#      "
#    user: root
#    env_file:
#      - .env_postgresql
#    depends_on:
#      - django
#    volumes:
#      - ./django:/property_rental
