version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile-sqlite
    command: >
      sh -c "
        rm -f /tmp/test_finished.lock &&
        sh /scripts/run_tests.sh &&
        touch /tmp/test_finished.lock
      "
    user: root
    env_file:
      - .env_sqlite
    volumes:
      - ./django:/property_rental
      - test-lock:/tmp
    restart: "no"

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - test-lock:/tmp
    depends_on:
      - tests
    entrypoint: [ "sh", "-c", "while [ ! -f /tmp/test_finished.lock ]; do echo 'Aguardando testes...'; sleep 50; done; echo 'Testes concluídos, iniciando Rabbitmq' && /usr/local/bin/docker-entrypoint.sh rabbitmq-server" ]

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
      - test-lock:/tmp
    ports:
      - "6380:6379"
    depends_on:
      - tests
    restart: "no"
    entrypoint: [ "sh", "-c", "while [ ! -f /tmp/test_finished.lock ]; do echo 'Aguardando testes...'; sleep 50; done; echo 'Testes concluídos, iniciando Redis' && /usr/local/bin/docker-entrypoint.sh redis-server" ]

  django:
    build:
      context: .
      dockerfile: Dockerfile-sqlite
    ports:
      - "8000:8000"
    volumes:
      - ./django:/property_rental
      - test-lock:/tmp
    command: >
      sh -c "
        sh /scripts/wait_for_services.sh  &&
        sh /scripts/collect_static.sh &&
        sh /scripts/migrate.sh &&
        sh /scripts/run_server.sh
      "
    user: root
    env_file:
      - .env_sqlite
    depends_on:
      - tests
      - rabbitmq
      - redis
    restart: "no"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-sqlite
    command: sh -c "/scripts/wait_for_services.sh celery -A property_rental worker --loglevel=info"
    env_file:
      - .env_sqlite
    volumes:
      - ./django:/property_rental
    depends_on:
      - tests
      - django
      - rabbitmq
      - redis
    user: root

volumes:
  test-lock:
  redis-data: