FROM python:3.13-alpine

# Define variáveis de ambiente
ENV PATH="/scripts:${PATH}"

# Instalar dependências do sistema para compilar o psycopg2 e outras dependências
RUN apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers musl-dev postgresql-dev libffi-dev make

# Copiar e instalar requisitos
COPY ./django/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Limpar qualquer conteúdo anterior da pasta /scripts antes de copiar
RUN rm -rf /scripts/*

# Cria o diretório da aplicação Django
RUN mkdir /django
COPY ./django /django
WORKDIR /django

# Cria o banco de dados SQLite se não existir
RUN [ ! -f /django/db.sqlite3 ] && cp /django/db.sqlite3.example /django/db.sqlite3 || true

# Copia os scripts e ajusta as permissões
COPY ./scripts /scripts
RUN chmod +x /scripts/*

# Cria diretórios para arquivos de mídia e estáticos
RUN mkdir -p /vol/web/media /vol/web/static

# Adiciona um usuário e ajusta permissões
RUN adduser -D user && \
    chown -R user:user /vol && \
    chmod -R 755 /vol/web

# Define o usuário padrão para rodar a aplicação
USER user

# Comando padrão para iniciar o contêiner Django
CMD ["sh", "scripts/entrypoint.sh"]